### PR TITLE
src: Make clippy happier

### PR DESCRIPTION
**Pull request by joaoantoniocardoso**

### CODE REVIEW

**Comment by joaoantoniocardoso** [comment]
lesson: I should run clippy way often

**Comment by patrickelectric** [comment]
> lesson: I should run clippy way often

Why are we not running on CI ?

**Comment by joaoantoniocardoso** [comment]
> > lesson: I should run clippy way often
> 
> Why are we not running on CI ?

It is, but it lacks permission to make annotations

**Comment by patrickelectric** [comment]
Did you check this ?
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs

**Review by patrickelectric — APPROVED** [review]

**Pull request merged**
